# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('page_numner', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
