# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='page_numner',
            new_name='page_number',
        ),
    ]
